BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'vertical'
        id: entries
    Label:
        size_hint_y: 0.1
        text: app.status

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.2
        Button:
            text: "Create Widgets"
            on_press: app.create_widgets()
        Button:
            text: "Clear Widgets"
            on_press: app.clear()